---
Name: phonelinkmodule
After:
  - '#cmsmodals'
---
SilverStripe\Admin\ModalController:
  link_modal_form_factories:
    EditorPhoneLink: Firebrand\PhoneLink\Forms\EditorPhoneLinkFormFactory
  extensions:
    - Firebrand\PhoneLink\Forms\PhoneLinkModalExtension
